### ISSUE TITLE
Obscured Zig errors in okra-node

### ISSUE THREAD

**Issue by garbados** [canvasxyz/okra-js#2]
Hi!

Using the NodeJS bindings, I'm encountering a strange, obscured error:

```
file:///home/garbados/code/okra-experiments/node_modules/@canvas-js/okra-node/lib/index.js:322
        return super.next();
                     ^

Error: MDB_BAD_TXN
    at Iterator.next (file:///home/garbados/code/okra-experiments/node_modules/@canvas-js/okra-node/lib/index.js:322:22)
    at Tree.nodes (file:///home/garbados/code/okra-experiments/node_modules/@canvas-js/okra-node/lib/index.js:296:69)
    at nodes.next (<anonymous>)
    at collect (file:///home/garbados/code/okra-experiments/node_modules/@canvas-js/okra/lib/utils.js:36:22)
    at async file:///home/garbados/code/okra-experiments/server.js:148:24
```

The quoted portion of `server.js` looks like this:

```js
const realized = await req.db.fetch((tree) => {
  return collect(tree.nodes(level, lowerBound, upperBound))
})
```

(`req.db` refers to a little wrapper; `db.fetch` passes a callback to `env.readTree` and resolves to the callback's return value.)

I understand `MDB_BAD_TXN` is an error from the [Zig implementation](https://github.com/canvasxyz/zig-lmdb/blob/16beae34ecd3062af87585893edf35331029be66/src/errors.zig#L33C5-L33C16) but to my eyes, I haven't the foggiest clue what I'm doing wrong.

Aside from a solution to my problem specifically, it would be nice if Zig errors could be made friendlier once they pass into NodeJS land. Any ideas?

**Comment by garbados** [comment]
For context, I'm writing an HTTP API for syncing prolly trees between node and the browser. I have get/set/delete working, and all the necessary methods scaffolded on both ends, but I'm having a hard time chewing through opaque errors like these.

**Comment by joeltg** [comment]
It’s actually an error forwarded from LMDB, which doesnt tell us much either - I copied the descriptions from the C LMDB source here: https://github.com/canvasxyz/zig-lmdb/blob/16beae34ecd3062af87585893edf35331029be66/src/errors.zig#L96C22-L96C22

Unless you’re using child transactions, Im not sure what it could be… maybe somehow the readTree callback is returning early (not awaiting everything that happens)? If you could distill it into something I can reproduce that would be a lot easier.

**Comment by garbados** [comment]
I was able to get it working on my end so I'll close the ticket. Skipping my wrapper and using readTree directly seemed to work, so my current theory is that my wrapper managed to break out of some vital context. I wish I had something reproducible for you; I'll follow up when my work exits the experimental stage.
