### ISSUE TITLE
question: Is the default hash a sha256 or blake3 or something else?

### ISSUE THREAD

**Issue by gobengo** [canvasxyz/okra-js#9]
The description on the okra repo [says](https://github.com/canvasxyz/okra) the hash at each node of the tree is a sha256 tree. In [places](https://github.com/canvasxyz/okra-js/blob/ece3dce41604fbc563025cc3ad75edefb4f4ff8b/packages/okra/src/utils.ts#L63) in this repo I see sha256 commented out and blake3 used.

Just so I understand what the 'hash' bytes are: is it a blake3 hash when using okra-js?

Secondarily, will this hash from okra-js be consistent with what folks get from the okra zig repo?

Thank you. This library works really well.

**Comment by joeltg** [comment]
thanks for asking, I forgot to update the readme to be clear about this!

The answer is blake3 - we had switched to sha256 for an earlier version but have reverted everything back to blake3 for the current database version ([`3`](https://github.com/canvasxyz/okra-js/blob/eeaceb698e2216d6486ecb84e256b58f9a59eb0f/packages/okra/src/constants.ts#L3)).

There were some other features in okra v3 that I haven't finished implementing for the Zig version, so it's still on sha256 / v2 at the moment, but I will get back to it soon.

**Comment by gobengo** [comment]
@joeltg Thanks for the clarification!
